Bulk read
12660-Robotters/OffseasonControl pull request #4
Opened 2023-02-27 22:33 UTC by cheeetoo

2023-02-27 22:36 UTC, foehammer127 requested changes
Based

2023-02-27 22:36 UTC, foehammer127 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/RobotContainer.java
No register?

2023-02-27 22:36 UTC, foehammer127 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/commands/BulkReadingClear.java
> +            module.clearBulkCache();
Not sure if this runs often enough

2023-02-27 22:40 UTC, cheeetoo commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/commands/BulkReadingClear.java
> +            module.clearBulkCache();
[it should run every control cycle](https://github.com/FIRST-Tech-Challenge/FtcRobotController/blob/0879b4797f7c9664731c9306926f713ef4ddfe5d/FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptMotorBulkRead.java#LL194C13-L194C13)

2023-02-27 22:44 UTC, cheeetoo commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot/RobotContainer.java
fixed

2023-03-01 17:59 UTC, foehammer127 commented
This is closed since it has behavior that we discussed in person.

2023-03-01 17:59 UTC, closed without merging